import {test} from 'node:test';
import assert from 'node:assert/strict';
import {makeState,applyCommand} from '../lib/engine-v2.ts';
const now=Date.parse('2026-09-23T12:00:00Z');
const run=(s,c,source='self',at=now)=>applyCommand(s,c,'test',source,at);
function setup(){return run(makeState(),{type:'register',candidateId:'a'},'candidate',now-90*86400000)}
function spins(){let s=setup();for(const kind of ['meal','tease','voucher'])s=run(s,{type:'spin',candidateId:'a',kind},'candidate');return s}
function hired(){let s=spins();s=run(s,{type:'application.submitted',candidateId:'a',selfId:'S'});return run(s,{type:'candidate.hired',candidateId:'a',employeeId:'E'})}
test('three spins before application; meal, teaser, then locked 50 GEL voucher',()=>{let s=setup();s=run(s,{type:'spin',candidateId:'a',kind:'meal'},'candidate');assert.ok(['coffee','hotdog'].includes(s.candidates[0].rewards[0].prize));assert.equal(s.candidates[0].rewards[1].state,'UNAVAILABLE');s=run(s,{type:'spin',candidateId:'a',kind:'tease'},'candidate');assert.ok(['try_again','other_gift'].includes(s.candidates[0].bonusOutcome));assert.equal(s.candidates[0].rewards[1].state,'AVAILABLE');s=run(s,{type:'spin',candidateId:'a',kind:'voucher'},'candidate');assert.equal(s.candidates[0].rewards[1].amount,50);assert.equal(s.candidates[0].rewards[1].state,'LOCKED');assert.throws(()=>run(s,{type:'spin',candidateId:'a',kind:'tease'},'candidate'),/REWARD_NOT_AVAILABLE/)});
test('candidate cannot self-confirm; hire activates both rewards',()=>{const s=spins();assert.throws(()=>run(s,{type:'application.submitted',candidateId:'a',selfId:'S'},'candidate'),/FORBIDDEN/);assert.equal(hired().candidates[0].rewards[1].state,'ACTIVE')});
test('redemption is one-time',()=>{let s=hired();const code=s.candidates[0].rewards[1].code;s=run(s,{type:'redeem',candidateId:'a',code},'manual');assert.throws(()=>run(s,{type:'redeem',candidateId:'a',code},'manual'),/CODE_NOT_ACTIVE/)});
test('duplicate verified applicant is rejected',()=>{let s=hired();s=run(s,{type:'register',candidateId:'b'},'candidate');assert.throws(()=>run(s,{type:'application.submitted',candidateId:'b',selfId:'S'}),/DUPLICATE_APPLICANT/)});
test('referral 250 requires one calendar month; duplicate event is idempotent',()=>{let s=setup();s=run(s,{type:'register',candidateId:'b',referralCode:s.candidates[0].referralCode},'candidate',now-60*86400000);s=run(s,{type:'application.submitted',candidateId:'b',selfId:'B'});s=run(s,{type:'candidate.hired',candidateId:'b',employeeId:'EB'});const cmd={type:'employment.month_completed',candidateId:'b',employeeId:'EB',startedAt:'2026-08-01T00:00:00Z',endedAt:'2026-09-01T00:00:00Z',eventId:'month-event-1'};assert.throws(()=>run(s,{...cmd,endedAt:'2026-08-15T00:00:00Z'}),/ONE_MONTH_REQUIRED/);s=run(s,cmd);assert.equal(s.candidates[0].rewards[2].state,'ACTIVE');assert.equal(s.candidates[0].rewards[2].amount,250);assert.deepEqual(run(s,cmd),s)});
test('hold and expiry block redemption',()=>{let s=hired();const code=s.candidates[0].rewards[0].code;s=run(s,{type:'hold',candidateId:'a',reason:'review required'},'manual');assert.throws(()=>run(s,{type:'redeem',candidateId:'a',code},'manual'),/ACCOUNT_HELD/);s=run(s,{type:'release',candidateId:'a',reason:'review complete'},'manual');assert.throws(()=>run(s,{type:'redeem',candidateId:'a',code},'manual',now+31*86400000),/CODE_NOT_ACTIVE/)});
