"use client";
import {useState,useEffect,useCallback} from 'react';
import {ArrowUpRight,ArrowRight,Gift,Coffee,LockKeyhole,Check,Users,Wallet,CircleHelp,ShieldCheck,Copy,Share2,LayoutDashboard,RefreshCw,X,Sparkles,ChevronRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {Toaster,toast} from 'sonner';
import PrizeWheel from './prize-wheel';
import AdminPanel from './recruiter';
import type {Candidate,Campaign,Reward} from '@/lib/engine';
type Data={demo:boolean;admin:boolean;userId:string;config:Campaign;candidates:Candidate[];referralCount:number};
const SELF='https://waymart.selfrecruit.ge/e8e7ca79-c3fc-475c-9c01-bfde96354572';
const label:Record<string,string>={AVAILABLE:'მზადაა გასახსნელად',UNAVAILABLE:'ჯერ არ გახსნილა',LOCKED:'აპლიკაციის შემდეგ გააქტიურდება',ACTIVE:'აქტიურია',REDEEMED:'გამოყენებულია',EXPIRED:'ვადა ამოიწურა',REVOKED:'გაუქმებულია'};
const prizeName=(r?:Reward)=>!r?'ყავა ან ჰოთდოგი':r.kind==='voucher'?'50₾-იანი ვაუჩერი':r.kind==='referral'?'250₾-იანი ბონუსი':r.prize==='coffee'?'ყავა':r.prize==='hotdog'?'ჰოთდოგი':'ყავა ან ჰოთდოგი';
export default function CandidateApp(){
 const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState('start'),[mode,setMode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[spinning,setSpinning]=useState(false),[rotation,setRotation]=useState(0),[modal,setModal]=useState(''),[reward,setReward]=useState<Reward|null>(null),[tease,setTease]=useState('');
 const load=useCallback(async()=>{if(!mode)return;try{const r=await fetch('/api/state?mode='+mode,{cache:'no-store'});const j=await r.json() as Data&{error?:string};if(!r.ok)throw Error(j.error);setData(j);setError('')}catch(e){setError((e as Error).message)}},[mode]);
 useEffect(()=>{const q=new URLSearchParams(location.search);setMode(q.get('mode')==='demo'?'demo':'live');if(location.hash==='#admin')setTab('admin')},[]);
 useEffect(()=>{if(!mode)return;let active=true;(async()=>{try{const q=new URLSearchParams(location.search);const r=await fetch('/api/session?mode='+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({referralCode:q.get('r')||undefined})});const j=await r.json() as {error?:string};if(!r.ok)throw Error(j.error);if(active)await load()}catch(e){if(active)setError((e as Error).message)}})();return()=>{active=false}},[mode,load]);
 useEffect(()=>{const f=()=>void load();window.addEventListener('focus',f);return()=>window.removeEventListener('focus',f)},[load]);
 const me=data?.candidates.find(x=>x.id===data.userId),meal=me?.rewards[0],voucher=me?.rewards[1],referral=me?.rewards[2];
 const mealOpened=!!meal&&meal.state!=='AVAILABLE',teaseOpened=!!me?.bonusOutcome,voucherOpened=!!voucher&&!['UNAVAILABLE','AVAILABLE'].includes(voucher.state),spinKind=!mealOpened?'meal':!teaseOpened?'tease':'voucher',wheelKind=spinKind==='meal'?'meal':'voucher';
 const link=typeof location!=='undefined'&&me?location.origin+'/?r='+me.referralCode+(mode==='demo'?'&mode=demo':''):'';
 const referrer=me?.referredBy&&data?data.candidates.find(x=>x.id===me.referredBy):undefined;
 const codeForSELF=me?'WayMart CLAIM: '+me.claimCode+' | REF: '+me.referralCode+(referrer?' | FROM: '+referrer.referralCode:''):'';
 async function spin(){if(busy||spinning||!me||voucherOpened||me.held)return;setBusy(true);try{const r=await fetch('/api/action?mode='+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'spin',kind:spinKind})});const j=await r.json() as {candidate:Candidate;error?:string};if(!r.ok)throw Error(j.error);const outcome=j.candidate.bonusOutcome||'';const result=spinKind==='tease'?null:j.candidate.rewards.find(x=>x.kind===spinKind)!;setSpinning(true);setRotation(v=>Math.ceil(v/360)*360+2520+(spinKind==='tease'?135:result?.prize==='hotdog'?90:0));setTimeout(()=>{setSpinning(false);if(result){setReward(result);setModal('won')}else{setTease(outcome);setModal('tease')}void load()},matchMedia('(prefers-reduced-motion: reduce)').matches?0:5200)}catch(e){toast.error((e as Error).message==='REWARD_NOT_AVAILABLE'?'ეს დატრიალება უკვე გამოყენებულია.':'დატრიალება ვერ შესრულდა. სცადე ხელახლა.');void load()}finally{setBusy(false)}}
 async function copy(value:string){try{await navigator.clipboard.writeText(value);toast.success('დაკოპირებულია')}catch{toast.error('კოდი შეგიძლია მონიშნო და ხელით დააკოპირო.')}}
 async function share(){try{if(navigator.share)await navigator.share({title:'შემოუერთდი WayMart-ის გუნდს',url:link});else await copy(link)}catch(e){if((e as Error).name!=='AbortError')toast.error('გაზიარება ვერ მოხერხდა')}}
 function selfURL(){const u=new URL(data?.config.selfUrl||SELF);if(me){u.searchParams.set('waymart_claim',me.claimCode);u.searchParams.set('waymart_referral_code',me.referralCode);if(referrer)u.searchParams.set('waymart_referred_by',referrer.referralCode)}return u.toString()}
 const view=(r?:Reward)=>{if(!r)return;if(r.state==='AVAILABLE'||r.state==='UNAVAILABLE'){setTab('start');return}setReward(r);setModal('reward')};
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>void}}).modelContext;if(!ctx)return;const c=new AbortController();void Promise.resolve(ctx.registerTool({name:'read_my_rewards',description:'Read candidate rewards and referral code without changing them.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({rewards:me?.rewards.map(({kind,state,prize})=>({kind,state,prize}))||[],referralCode:me?.referralCode})},{signal:c.signal})).catch(()=>{});return()=>c.abort()},[me]);
 return <><Toaster richColors position="top-center"/><header className="topbar"><a href="/" className="brand" aria-label="WayMart მთავარი"><span className="brand-mark"><img src="/waymart-logo.jpg" alt=""/></span><span className="brand-name">ვეი მარტი<small>RECRUIT & WIN</small></span></a><span className="brand-caption">კარგი ამბები იწყება აქ.</span><button className="header-help plain" onClick={()=>setModal('terms')}>როგორ მუშაობს <CircleHelp size={17}/></button></header>
 <main className="shell"><div className="page-heading"><div><p className="eyebrow"><span className="red-dot"/> WAYMART RECRUIT & WIN</p><h1>სამი დატრიალება. ბოლოს 50₾ ვაუჩერი.</h1></div><span className="tag">მოლარე-კონსულტანტი • თბილისი</span></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="main-nav" variant="line"><TabsTrigger value="start"><Sparkles size={18}/> ბორბალი</TabsTrigger><TabsTrigger value="wallet"><Wallet size={18}/> ჩემი საჩუქრები</TabsTrigger><TabsTrigger value="referral"><Users size={18}/> მოიწვიე მეგობარი</TabsTrigger>{tab==='admin'&&<TabsTrigger value="admin">მართვა</TabsTrigger>}</TabsList>
 <TabsContent value="start"><section className="experience-hero"><div className="hero-copy"><span className="pill"><Gift size={14}/>{voucherOpened?'ვაუჩერი გახსნილია':!mealOpened?'დატრიალება 01 / 03':!teaseOpened?'დატრიალება 02 / 03':'დატრიალება 03 / 03'}</span><h2>{voucherOpened?<>ვაუჩერი შენია.<br/><em>ახლა SELF-ში.</em></>:!mealOpened?<>დაატრიალე.<br/><em>პირველი საჩუქარი.</em></>:!teaseOpened?<>კიდევ სცადე.<br/><em>ვაუჩერი ახლოსაა.</em></>:<>ბოლო დატრიალება.<br/><em>50₾ გელოდება.</em></>}</h2><p>{voucherOpened?'შეავსე აპლიკაცია SELF-ში და გახდი WayMart-ის გუნდის წევრი, რომ ვაუჩერი გამოიყენო.':!mealOpened?'პირველ დატრიალებაზე მიიღებ ყავას ან ჰოთდოგს.':'მეორე დატრიალება გასართობია: შეიძლება “კიდევ სცადე” ან სხვა საჩუქარი. მესამე დატრიალებაზე იხსნება 50₾ ვაუჩერი.'}</p><div className="spin-progress three"><span className={mealOpened?'finished':'current'}>{mealOpened?<Check size={14}/>:1}<b>ყავა ან ჰოთდოგი</b></span><i/><span className={teaseOpened?'finished':mealOpened?'current':''}>{teaseOpened?<Check size={14}/>:2}<b>კიდევ სცადე</b></span><i/><span className={voucherOpened?'finished':teaseOpened?'current':''}>{voucherOpened?<Check size={14}/>:3}<b>50₾ ვაუჩერი</b></span></div>{voucherOpened&&<a className="primary-button self-cta" href={selfURL()} target="_blank" rel="noopener noreferrer">შეავსე აპლიკაცია SELF-ში <ArrowUpRight size={19}/></a>}<div className="hero-trust"><ShieldCheck size={17}/><span>საჩუქრები გამოიყენება აპლიკაციის<br/><b>და დასაქმების დადასტურების შემდეგ.</b></span></div></div>
 <PrizeWheel rotation={rotation} spinning={spinning} disabled={busy||spinning||!me||voucherOpened||!!me?.held} demo={false} kind={wheelKind} completed={voucherOpened} stepLabel={!mealOpened?'1 / 3':!teaseOpened?'2 / 3':'3 / 3'} floatTitle={!mealOpened?'პირველი საჩუქარი':!teaseOpened?'მეორე შანსი':'ბოლო დატრიალება'} floatPrize={!mealOpened?'ყავა ან ჰოთდოგი':!teaseOpened?'კიდევ სცადე / სხვა საჩუქარი':'50₾-იანი ვაუჩერი'} onSpin={()=>void spin()}/></section>
 {error&&<div role="status" className="notice neutral"><span>{error==='REFERRAL_NOT_FOUND'?'მოწვევის კოდი ვერ მოიძებნა. გადაამოწმე ბმული.':'ბორბალთან დაკავშირება ვერ მოხერხდა.'}</span><button className="plain text-link" onClick={()=>location.reload()}>ხელახლა ცდა <RefreshCw size={15}/></button></div>}
 <div className="journey-strip">{[['01','დაატრიალე 3-ჯერ','ვაუჩერამდე მიდიხარ'],['02','შეავსე აპლიკაცია','პირდაპირ SELF-ში'],['03','შემოუერთდი გუნდს','დასაქმების დადასტურება'],['04','გამოიყენე საჩუქრები','ერთჯერადი კოდით']].map(([n,t,d],i)=>i===1?<a href={selfURL()} target="_blank" rel="noopener noreferrer" key={n}><span>{n}</span><div><b>{t}</b><small>{d}</small></div><ArrowUpRight size={16}/></a>:<button key={n} onClick={()=>i===0?document.querySelector('.premium-spin-button')?.scrollIntoView({behavior:'smooth',block:'center'}):setTab('wallet')}><span>{n}</span><div><b>{t}</b><small>{d}</small></div><ChevronRight size={16}/></button>)}</div>
 <div className="section-title"><div><p className="eyebrow">პატარა ბონუსი დიდი დასაწყისისთვის</p><h3>შენი საჩუქრები.</h3></div><button className="plain text-link" onClick={()=>setTab('wallet')}>ჩემი საფულე <ArrowUpRight size={17}/></button></div>
 <section className="reward-grid"><button className="reward-card meal-card" onClick={()=>view(meal)}><div className="reward-info"><span className="eyebrow">პირველი დატრიალება</span><h3>{mealOpened?prizeName(meal):<>ყავა ან<br/>ჰოთდოგი.</>}</h3><p>გემრიელი დასაწყისი WayMart-ისგან</p><span className="status">{mealOpened?label[meal!.state]:'დაატრიალე და გაიგე'}<ArrowUpRight size={14}/></span></div><img className="hotdog-photo" src="/hotdog.jpg" alt="WayMart-ის ჰოთდოგი"/></button>
 <button className="reward-card voucher-card" onClick={()=>view(voucher)}><div className="reward-info"><span className="eyebrow">მესამე დატრიალება</span><h3>შენი ახალი<br/>დასაწყისისთვის.</h3><p>50₾-იანი WayMart ვაუჩერი</p><span className="status">{voucherOpened?label[voucher!.state]:teaseOpened?'დაატრიალე მესამედ':'გაიხსნება მეორე ცდის შემდეგ'}<LockKeyhole size={13}/></span></div><div className="visual-ticket"><span>WAYMART</span><b>50<small>₾</small></b><i>გუნდის ახალ წევრს</i></div></button></section>
 <button className="referral-promo" onClick={()=>setTab('referral')}><span className="referral-promo-icon"><Users size={28}/></span><div><span className="eyebrow">რეკომენდატორის ბონუსი</span><h3>კარგი გუნდი მეგობრით იწყება.</h3><p>მოიწვიე მეგობარი. როცა ის მინიმუმ 1 თვეს იმუშავებს, მიიღე 250₾.</p></div><strong>250<span>₾</span></strong><ArrowUpRight size={23}/></button>
 </TabsContent>
 <TabsContent value="wallet"><div className="section-title"><h3>ჩემი საჩუქრები.</h3><button aria-label="განახლება" className="icon-button" onClick={()=>void load()}><RefreshCw size={18}/></button></div><div className="wallet-portal"><article className="wallet-hero-ticket"><span>WAYMART VOUCHER</span><strong>50₾</strong><p>{voucherOpened?'ვაუჩერი გახსნილია. გააქტიურდება დასაქმების დადასტურების შემდეგ.':teaseOpened?'დაგრჩა ბოლო დატრიალება ვაუჩერისთვის.':'ვაუჩერი იხსნება მესამე დატრიალებაზე.'}</p><button className="primary-button" disabled={!me||voucherOpened} onClick={()=>setTab('start')}>{voucherOpened?'ვაუჩერის სტატუსი':'ბორბალზე დაბრუნება'}<ArrowRight size={17}/></button></article><div className="wallet-mini-grid">{[meal,voucher].map((r,i)=><article className={'wallet-mini-card '+(i?'voucher':'')} key={i}><span>{i?'ვაუჩერი':'პირველი საჩუქარი'}</span><b>{i?'50₾':prizeName(r)}</b><small>{r?label[r.state]:'იტვირთება'}</small><button className="plain text-link" disabled={!r} onClick={()=>view(r)}>{r?.state==='ACTIVE'?'კოდის ნახვა':'დეტალები'} <ArrowRight size={14}/></button></article>)}</div></div>
 <article className="panel"><h3>შემდეგი ნაბიჯი</h3><div className="application-progress"><span className={me?.applied?'complete':''}>{me?.applied?<Check size={18}/>:<LockKeyhole size={18}/>} აპლიკაცია SELF-ში</span><span className={me?.hired?'complete':''}>{me?.hired?<Check size={18}/>:<LockKeyhole size={18}/>} WayMart-ის გუნდის წევრი</span></div>{!me?.hired&&<><p className="muted">SELF-ის „კომენტარი“ ველში ჩაწერე ეს კოდი, რომ რეკრუტერმა შენი საჩუქრები განაცხადს დაუკავშიროს.</p><div className="referral-link"><input aria-label="SELF-ის კომენტარის კოდი" value={codeForSELF} readOnly/><button aria-label="კოდის კოპირება" onClick={()=>copy(codeForSELF)}><Copy size={18}/></button></div><a className="primary-button" href={selfURL()} target="_blank" rel="noopener noreferrer">აპლიკაციის შევსება <ArrowUpRight size={18}/></a></>}</article></TabsContent>
 <TabsContent value="referral"><section className="referral-layout"><article className="referral-hero panel"><span className="pill light"><Users size={15}/> 250₾ მეგობრის მოწვევაზე</span><h2>გაუზიარე ბმული.<br/><em>მეგობარი დაიწყებს — შენ მიიღებ.</em></h2><p>გაუგზავნე ბმული მეგობარს. თუ ის ამ ბმულით შემოვა, შეავსებს აპლიკაციას და WayMart-ში 1 თვეს იმუშავებს, შენთვის 250₾ გააქტიურდება.</p><div className="referral-steps"><span><b>1</b> გაუზიარე ბმული</span><span><b>2</b> მეგობარი ავსებს აპლიკაციას</span><span><b>3</b> 1 თვის შემდეგ იღებ 250₾</span></div><div className="referral-code"><span>შენი მოსაწვევი კოდი</span><b>{me?.referralCode||'იტვირთება…'}</b></div><div className="referral-link"><input aria-label="შენი მოსაწვევი ბმული" readOnly value={link}/><button aria-label="ბმულის კოპირება" disabled={!me} onClick={()=>copy(link)}><Copy size={18}/></button></div><button className="primary-button" disabled={!me} onClick={share}><Share2 size={17}/> გაუგზავნე მეგობარს</button><p className="subtle"><ShieldCheck size={16}/> ბონუსი ავტომატურად არ გაიცემა მხოლოდ share-ზე. რეკრუტერი ადასტურებს, რომ მეგობარი შენი ბმულით მოვიდა და 1 თვე იმუშავა.</p></article><aside className="panel referral-summary"><div className="large-number">{data?.referralCount||0}<Users size={30}/></div><h3>შენი მოწვევები</h3><p>აქ ჩანს რამდენმა მეგობარმა შეავსო აპლიკაცია შენი ბმულით.</p><div className="mini-voucher"><span>რეკომენდატორის ბონუსი</span><b>250₾</b><small>{referral?.state==='ACTIVE'?'ბონუსი აქტიურია':'აქტიურდება მეგობრის 1 თვის მუშაობის შემდეგ'}</small>{referral?.state==='ACTIVE'&&<button className="primary-button" onClick={()=>view(referral)}>ბონუსის ნახვა</button>}</div></aside></section><section className="panel"><h3>როგორ იცის სისტემა, ვისგან მოვიდა?</h3><p className="muted">შენს ბმულში დევს REF კოდი. მეგობარი ამ ბმულით რომ შემოვა, მისი განაცხადი შენს კოდს უკავშირდება. SELF-ში გადასვლისას ასევე მიდის CLAIM და REF კოდები, რომ რეკრუტერმა მარტივად გადაამოწმოს.</p></section></TabsContent>
 <TabsContent value="admin"><AdminPanel mode={mode||'live'} onChange={load}/></TabsContent></Tabs>
 {mode==='demo'&&<div className="demo-strip"><span>სატესტო გარემო — რეალური ჯილდოები არ გაიცემა.</span><a href="/">კანდიდატის გვერდი</a></div>}
 <section className="bottom-note"><div><ShieldCheck/><p><b>შენი მომავალი იწყება პატარა ნაბიჯით.</b><br/><span>დაატრიალე, შეავსე აპლიკაცია და შემოუერთდი WayMart-ს.</span></p></div><button className="plain text-link" onClick={()=>setModal('terms')}>კამპანიის პირობები <ArrowRight size={16}/></button></section><footer><span>© 2026 WayMart</span><span>ერთად იწყება კარგი ამბავი.</span><button className="plain" onClick={()=>{setTab('admin');location.hash='admin'}}>რეკრუტერის პანელი</button></footer></main>
 <Dialog open={!!modal} onOpenChange={v=>{if(!v)setModal('')}}><DialogContent showCloseButton={false} className={'wm-dialog '+((modal==='won'||modal==='reward')&&reward?'win-dialog':'')}><DialogClose className="dialog-close" aria-label="დახურვა"><X size={20}/></DialogClose>
 {(modal==='won'||modal==='reward')&&reward&&<><div className={'prize-reveal '+reward.kind}><span className="burst-dot"/><span className="burst-dot"/><span className="burst-dot"/><span className="burst-dot"/><div className="reveal-ticket"><small>WAYMART</small><strong>{reward.kind==='voucher'?'50₾':reward.kind==='referral'?'250₾':reward.prize==='coffee'?'ყავა':'ჰოთდოგი'}</strong><em>{reward.kind==='voucher'?'გუნდის ახალ წევრს':reward.kind==='referral'?'რეკომენდატორს':'პირველი საჩუქარი'}</em></div></div><DialogTitle>{reward.kind==='voucher'?'50₾-იანი ვაუჩერი გახსნილია!':reward.kind==='referral'?'250₾ რეკომენდატორის ბონუსი':prizeName(reward)+' შენია!'}</DialogTitle><DialogDescription>{reward.state==='LOCKED'?'საჩუქარი შენახულია. შემდეგი ნაბიჯი: შეავსე აპლიკაცია SELF-ში და გახდი WayMart-ის გუნდის წევრი.':label[reward.state]}</DialogDescription>
 {modal==='won'&&reward.kind==='meal'&&<button className="primary-button reveal-primary" onClick={()=>{setModal('');document.querySelector('.premium-spin-button')?.scrollIntoView({behavior:'smooth',block:'center'})}}>კიდევ სცადე <ArrowRight size={18}/></button>}
 {reward.state==='LOCKED'&&<><div className="claim-hint reveal-claim"><p>ჩასვი ეს კოდი SELF-ის „კომენტარი“ ველში:</p><div className="referral-link"><input aria-label="აპლიკაციის კოდი" readOnly value={codeForSELF}/><button aria-label="კოდის კოპირება" onClick={()=>copy(codeForSELF)}><Copy size={18}/></button></div></div><a className={reward.kind==='voucher'?'primary-button reveal-primary':'secondary-button'} href={selfURL()} target="_blank" rel="noopener noreferrer">შეავსე აპლიკაცია SELF-ში <ArrowUpRight size={17}/></a></>}
 {reward.state==='ACTIVE'&&<><div className="pin-box"><span>ერთჯერადი განაღდების კოდი</span><strong>{reward.code}</strong><small>{reward.expiresAt?new Date(reward.expiresAt).toLocaleDateString('ka-GE')+'-მდე':''}</small></div><p className="muted">აჩვენე უფლებამოსილ თანამშრომელს. კოდი გამოიყენება ერთხელ.</p></>}
 </>}
 {modal==='tease'&&<><div className="win-burst tease-burst"><Sparkles size={48}/><span>{tease==='other_gift'?'სხვა საჩუქარი ახლოსაა!':'კიდევ სცადე!'}</span></div><DialogTitle>{tease==='other_gift'?'კარგია, მესამე დატრიალებაზე ვაუჩერია.':'ვაუჩერს ცოტათი გადასცდა.'}</DialogTitle><DialogDescription>დაგრჩა ბოლო დატრიალება — 50₾-იანი ვაუჩერი იხსნება მესამე ცდაზე.</DialogDescription><button className="primary-button reveal-primary" onClick={()=>{setModal('');document.querySelector('.premium-spin-button')?.scrollIntoView({behavior:'smooth',block:'center'})}}>ბოლო დატრიალება <ArrowRight size={18}/></button></>}
 {modal==='terms'&&<><DialogTitle>კამპანიის პირობები</DialogTitle><DialogDescription>3 დატრიალება კანდიდატისთვის და ცალკე ბონუსი რეკომენდატორისთვის.</DialogDescription><div className="terms"><h4>1. სამი დატრიალება</h4><p>პირველი დატრიალება ხსნის ყავას ან ჰოთდოგს. მეორე დატრიალება არის დამატებითი შანსი: “კიდევ სცადე” ან სხვა საჩუქრის tease. მესამე დატრიალებაზე იხსნება 50₾-იანი ვაუჩერი.</p><h4>2. გამოყენება</h4><p>საჩუქრები ინახება დაბლოკილი. ისინი აქტიურდება SELF-ში აპლიკაციისა და WayMart-ში დასაქმების დადასტურების შემდეგ. გვერდზე დაბრუნება დადასტურებად არ ითვლება.</p><h4>3. რეკომენდატორის 250₾</h4><p>მეგობარი შენი ბმულით უნდა შემოვიდეს, შეავსოს აპლიკაცია, დასაქმდეს და მინიმუმ ერთი კალენდარული თვე იმუშაოს. ბონუსს რეკრუტერი ან დამოწმებული ინტეგრაცია ააქტიურებს.</p><h4>4. ერთჯერადი განაღდება</h4><p>აქტიური საჩუქარი გამოიყენება ერთხელ, მისი ვადის ფარგლებში. მოქმედების ვადაა აქტივაციიდან {data?.config.expiryDays||30} დღე. დუბლირებული განაცხადები და საკუთარი თავის მოწვევა არ დაიშვება.</p><h4>5. პროგრესი და მონაცემები</h4><p>პროგრესი ინახება სერვერზე და უკავშირდება ამ ბრაუზერის დაცულ 30-დღიან სესიის ჩანაწერს. ავტორიზაცია არ გჭირდება. ბრაუზერის მონაცემების წაშლისას წვდომის აღსადგენად მიმართე რეკრუტერს განაცხადის კოდით.</p></div></>}
 </DialogContent></Dialog></>
}



