export type RewardState='UNAVAILABLE'|'AVAILABLE'|'LOCKED'|'ACTIVE'|'REDEEMED'|'EXPIRED'|'REVOKED';
export type Reward={kind:'meal'|'voucher'|'referral';state:RewardState;prize?:'coffee'|'hotdog';code?:string;issuedAt?:number;expiresAt?:number;redeemedAt?:number;amount:number};
export type Candidate={id:string;name:string;selfId?:string;employeeId?:string;applied:boolean;hired:boolean;shiftCompleted:boolean;monthCompleted?:boolean;employmentStartedAt?:string;referralCode:string;claimCode:string;referredBy?:string;createdAt:number;held:boolean;bonusOutcome?:'try_again'|'other_gift';rewards:Reward[]};
export type Audit={id:string;at:number;actor:string;source:string;type:string;candidateId?:string;reason?:string};
export type Campaign={name:string;active:boolean;voucherAmount:number;expiryDays:number;selfUrl:string;capacity:number;referralAmount:number};
export type State={schemaVersion:2;config:Campaign;candidates:Candidate[];events:Audit[];processed:string[];createdAt:number};
export type Command={type:string;candidateId?:string;name?:string;referralCode?:string;selfId?:string;employeeId?:string;eventId?:string;startedAt?:string;endedAt?:string;firstShift?:boolean;kind?:string;code?:string;reason?:string;config?:Partial<Campaign>};
export class RuleError extends Error{constructor(public code:string,public status=409){super(code)}}
export const SELF_URL='https://waymart.selfrecruit.ge/e8e7ca79-c3fc-475c-9c01-bfde96354572';
export const makeState=():State=>({schemaVersion:2,config:{name:'შენი ახალი დასაწყისი',active:true,voucherAmount:50,referralAmount:250,expiryDays:30,selfUrl:SELF_URL,capacity:1000},candidates:[],events:[],processed:[],createdAt:Date.now()});
const need=(ok:unknown,code:string)=>{if(!ok)throw new RuleError(code)};
const randomCode=(prefix:string)=>prefix+crypto.randomUUID().replaceAll('-','').slice(0,12).toUpperCase();
export function expire(s:State,now=Date.now()){for(const c of s.candidates)for(const r of c.rewards)if(r.state==='ACTIVE'&&r.expiresAt&&r.expiresAt<=now)r.state='EXPIRED';return s}
export function nextMonth(value:string){const d=new Date(value);const day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+1);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));return d.getTime()}
export function applyCommand(input:State,cmd:Command,actor:string,source:string,now=Date.now()):State{
 const s=expire(structuredClone(input),now);if(cmd.eventId&&s.processed.includes(cmd.eventId))return s;
 const privileged=['self','manual','demo'].includes(source),c=s.candidates.find(x=>x.id===cmd.candidateId);
 const get=()=>{need(c,'CANDIDATE_NOT_FOUND');return c!};
 const activate=(x:Candidate)=>{for(const r of x.rewards)if(r.kind!=='referral'&&r.state==='LOCKED'&&x.applied&&x.hired&&!x.held){r.state='ACTIVE';r.expiresAt=now+s.config.expiryDays*86400000}};
 switch(cmd.type){
 case 'register':{need(s.config.active,'CAMPAIGN_PAUSED');need(cmd.candidateId,'NAME_REQUIRED');if(c)return s;need(s.candidates.length<s.config.capacity,'CAPACITY_REACHED');const ref=cmd.referralCode?s.candidates.find(x=>x.referralCode===cmd.referralCode):undefined;need(!cmd.referralCode||ref,'REFERRAL_NOT_FOUND');need(!ref||ref.id!==cmd.candidateId,'SELF_REFERRAL');
 let referralCode=randomCode('WM-');while(s.candidates.some(x=>x.referralCode===referralCode))referralCode=randomCode('WM-');
 s.candidates.push({id:cmd.candidateId!,name:cmd.name?.trim().slice(0,80)||'კანდიდატი',applied:false,hired:false,shiftCompleted:false,held:false,referralCode,claimCode:randomCode('CLAIM-'),referredBy:ref?.id,createdAt:now,rewards:[{kind:'meal',state:'AVAILABLE',amount:0},{kind:'voucher',state:'UNAVAILABLE',amount:50},{kind:'referral',state:'UNAVAILABLE',amount:250}]});break}
 case 'spin':{need(s.config.active,'CAMPAIGN_PAUSED');const x=get();need(!x.held,'ACCOUNT_HELD');if(cmd.kind==='tease'){need(x.rewards[0]?.state==='LOCKED'&&!x.bonusOutcome,'REWARD_NOT_AVAILABLE');x.bonusOutcome=crypto.getRandomValues(new Uint8Array(1))[0]%2===0?'try_again':'other_gift';x.rewards[1].state='AVAILABLE';break}need(cmd.kind==='meal'||cmd.kind==='voucher','REWARD_NOT_AVAILABLE');const r=x.rewards.find(y=>y.kind===cmd.kind);need(r?.state==='AVAILABLE','REWARD_NOT_AVAILABLE');r!.state='LOCKED';r!.issuedAt=now;r!.code=randomCode('WMR-')+randomCode('');if(r!.kind==='meal'){r!.prize=crypto.getRandomValues(new Uint8Array(1))[0]%2===0?'coffee':'hotdog'}activate(x);break}
 case 'application.submitted':{need(privileged,'FORBIDDEN');const x=get();need(cmd.selfId?.trim(),'SELF_ID_REQUIRED');need(!s.candidates.some(y=>y.id!==x.id&&y.selfId===cmd.selfId),'DUPLICATE_APPLICANT');need(!x.selfId||x.selfId===cmd.selfId,'IDENTITY_CONFLICT');x.selfId=cmd.selfId;x.applied=true;activate(x);break}
 case 'candidate.hired':{need(privileged,'FORBIDDEN');const x=get();need(x.applied,'APPLICATION_REQUIRED');need(cmd.employeeId?.trim(),'EMPLOYEE_ID_REQUIRED');need(!s.candidates.some(y=>y.id!==x.id&&y.employeeId===cmd.employeeId),'DUPLICATE_EMPLOYEE');need(!x.employeeId||x.employeeId===cmd.employeeId,'IDENTITY_CONFLICT');x.employeeId=cmd.employeeId;x.hired=true;activate(x);break}
 case 'employment.month_completed':{need(privileged,'FORBIDDEN');const x=get();need(x.hired,'HIRE_REQUIRED');need(x.employeeId===cmd.employeeId,'EMPLOYEE_MISMATCH');const start=Date.parse(cmd.startedAt||''),end=Date.parse(cmd.endedAt||'');need(Number.isFinite(start)&&Number.isFinite(end)&&end>=nextMonth(cmd.startedAt!)&&(source==='demo'||end<=now)&&start>=x.createdAt,'ONE_MONTH_REQUIRED');x.monthCompleted=true;x.employmentStartedAt=cmd.startedAt;const ref=s.candidates.find(y=>y.id===x.referredBy);if(ref){const r=ref.rewards[2];if(r.state==='UNAVAILABLE'){r.state='ACTIVE';r.issuedAt=now;r.expiresAt=now+s.config.expiryDays*86400000;r.code=randomCode('REF-')+randomCode('')}}break}
 case 'redeem':{need(privileged,'FORBIDDEN');const x=get();need(!x.held,'ACCOUNT_HELD');const r=x.rewards.find(y=>y.code===cmd.code);need(r&&r.state==='ACTIVE','CODE_NOT_ACTIVE');r!.state='REDEEMED';r!.redeemedAt=now;break}
 case 'hold':case 'release':{need(privileged,'FORBIDDEN');need(cmd.reason&&cmd.reason.trim().length>=8,'REASON_REQUIRED');const x=get();x.held=cmd.type==='hold';if(!x.held)activate(x);break}
 case 'revoke':{need(privileged,'FORBIDDEN');need(cmd.reason&&cmd.reason.trim().length>=8,'REASON_REQUIRED');const r=get().rewards.find(y=>y.kind===cmd.kind);need(r&&r.state!=='REDEEMED','CANNOT_REVOKE');r!.state='REVOKED';break}
 case 'config':{need(source==='manual'||source==='demo','FORBIDDEN');const v=cmd.config||{};need(v.expiryDays===undefined||(Number.isInteger(v.expiryDays)&&v.expiryDays>=1&&v.expiryDays<=365),'INVALID_EXPIRY');need(v.selfUrl===undefined||/^https:\/\//.test(v.selfUrl),'HTTPS_REQUIRED');s.config={...s.config,...v,voucherAmount:50,referralAmount:250,capacity:1000};break}
 default:throw new RuleError('UNKNOWN_ACTION',400)
 }
 if(cmd.eventId)s.processed.push(cmd.eventId);s.events.push({id:crypto.randomUUID(),at:now,actor,source,type:cmd.type,candidateId:cmd.candidateId,reason:cmd.reason});need(s.events.length<20000,'ARCHIVE_REQUIRED');return s
}
export function metrics(s:State){const c=s.candidates;return{registered:c.length,applied:c.filter(x=>x.applied).length,referrals:c.filter(x=>x.applied&&x.referredBy).length,hired:c.filter(x=>x.hired).length,completed:c.filter(x=>x.monthCompleted).length,redeemed:c.flatMap(x=>x.rewards).filter(x=>x.state==='REDEEMED').length,liability:c.flatMap(x=>x.rewards).filter(x=>['ACTIVE','LOCKED'].includes(x.state)).reduce((n,r)=>n+r.amount,0),held:c.filter(x=>x.held).length}}
