import {neon} from '@neondatabase/serverless';
import {applyCommand,makeState,expire,RuleError,type State,type Command} from './engine';
type Row={payload:string;version:number};
const databaseUrl=()=>process.env.DATABASE_URL||process.env.POSTGRES_URL||'';
async function local(){if(process.env.VERCEL)throw new RuleError('STORAGE_UNAVAILABLE',503);const {DatabaseSync}=await import('node:sqlite');const {mkdirSync}=await import('node:fs');mkdirSync('.data',{recursive:true});const db=new DatabaseSync('.data/waymart-v2.sqlite');db.exec('PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS campaigns_v2(id TEXT PRIMARY KEY,version INTEGER NOT NULL DEFAULT 0,payload TEXT NOT NULL,updated_at INTEGER NOT NULL)');return db}
export async function load(scope:string){const payload=JSON.stringify(makeState()),url=databaseUrl();let row:Row|undefined;if(url){const sql=neon(url);await sql.query('INSERT INTO campaigns_v2(id,version,payload,updated_at) VALUES($1,0,$2,$3) ON CONFLICT(id) DO NOTHING',[scope,payload,Date.now()]);row=(await sql.query('SELECT payload,version FROM campaigns_v2 WHERE id=$1',[scope]))[0] as Row}else{const db=await local();try{db.prepare('INSERT OR IGNORE INTO campaigns_v2(id,version,payload,updated_at) VALUES(?,0,?,?)').run(scope,payload,Date.now());row=db.prepare('SELECT payload,version FROM campaigns_v2 WHERE id=?').get(scope) as Row|undefined}finally{db.close()}}if(!row)throw new RuleError('STORAGE_UNAVAILABLE',503);return{state:expire(JSON.parse(row.payload) as State),version:row.version}}
export async function mutate(scope:string,cmd:Command,actor:string,source:string){for(let i=0;i<8;i++){const {state,version}=await load(scope);const next=applyCommand(state,cmd,actor,source);const payload=JSON.stringify(next),url=databaseUrl();let changed=false;if(url){const sql=neon(url);changed=(await sql.query('UPDATE campaigns_v2 SET payload=$1,version=version+1,updated_at=$2 WHERE id=$3 AND version=$4 RETURNING version',[payload,Date.now(),scope,version])).length===1}else{const db=await local();try{changed=db.prepare('UPDATE campaigns_v2 SET payload=?,version=version+1,updated_at=? WHERE id=? AND version=?').run(payload,Date.now(),scope,version).changes===1}finally{db.close()}}if(changed)return next}throw new RuleError('RETRY_CONFLICT',409)}
export function setting(key:string){return process.env[key]||''}

